Backend/chunkfile/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name='register')
]

Backend/chunkfile/chunkfile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('modders/', admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include('accounts.urls')),
    path("split/", include("split_file.urls")),
]

Backend/chunkfile/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path("", views.home, name="home"),
    path('documentation', views.documentation, name='documentation'),
    path("new_features/", views.features, name="features"),
    ]
#if settings.DEBUG:
    #creates a last urlpattern - with the media url, so, whatever path is in the media_url is made a url pattern
    #
        #urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/chunkfile/split_file/urls.py
from django.urls import path
from . import views

app_name = 'split_file'
urlpatterns = [
    path("", views.split_home, name='split_home'),
    path("csv/", views.split_csv, name='split_csv'),
    path("json/", views.split_json, name='split_json'),
]

Backend/chunkfile/accounts/models.py
from django.db import models

# Create your models here.

Backend/chunkfile/main/models.py
from django.db import models

# Create your models here.

Backend/chunkfile/split_file/models.py
from django.db import models

# Create your models here.

Backend/chunkfile/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
        

Backend/chunkfile/main/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
        

Backend/chunkfile/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm 
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


    #login user view
def loginPage(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('main:home')
            else:
                messages.info(request, "Password or email is incorrect")
                
        return render(request, 'accounts/login.html')
    
    #log-out view
def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

    #register-user view
def registerPage(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        form = CreateUserForm()
        
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('accounts:login')
                
        context = {'form':form}
        return render(request, 'accounts/sign-up.html', context)

Backend/chunkfile/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


@login_required(login_url="accounts:login")
def home(request):
    return render(request, "main/home.html")

def documentation(request):
    return render(request, "main/documentation.html")
def features(request):
    return render(request, 'main/features.html')

Backend/chunkfile/split_file/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url="accounts:login")
def split_home(request):
    return render(request, 'split_home.html')
def split_csv(request):
    return render(request, 'split_file/split_csv.html')
def split_json(request):
    return render(request, 'split_file/split_json.html')

Backend/chunkfile/accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <style>
</style>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <h1>Log in</h1>
        <div class="inset">
          {% for message in messages %}
            <p id="message">{{message}}</p>
          {% endfor %}
        <p>
          <label for="username"></label>
          <input type="text" name="username" placeholder="Username"/>
        </p>
        <p>
          <label for="username"></label>
          <input type="password" name="password" placeholder="Password"/>
        </p>
        </div>
        <p class="p-container">
          <span>Forgot password ?</span>
          <span>Don't have an account? <a href="{% url 'accounts:register' %}">Sign up</a> </span>
          <input type="submit" name="go" id="go" value="Log in">
        </p>
      </form>

</body>
</html>

Backend/chunkfile/accounts/templates/accounts/sign-in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/signin.css' %}" />
    <title>Sign In</title>
  </head>

  <body>
    <section>
      <div class="image-section">
        <img src="#" alt="" />
      </div>

      <div class="form-section">
        <header>
          <p class="header-text">Hello Again!</p>
          <p class="header-sub-text">
            Welcome back, you've <br />
            been missed!
          </p>
        </header>

        <form action="#" method="POST">
          {% csrf_token %}
          <h1 width="30%">Sign In</h1>
          <hr width="30%" />

          {% for message in messages %}
          <p id="message">{{message}}</p>
          {% endfor %}

        <p>
            <label for="username">Username</label>
          <input type="text" name="username" placeholder="Username" />
        </p>
          
          
          <p>
            <label for="password">Password</label>
            <input
              type="password"
              name="password"
              placeholder="Password"
              required
            />
          </p>
        <p>
            <a href="#" class="forgotten-password"> Forgotten Password </a>
        </p>
        <p style="text-align: center;">
            <span class="">Don't have an account?</span>
            <a href="{% url 'accounts:register' %}" 
                style="text-decoration:none;">Sign Up</a>
        </p>
          

          <input type="submit" class="btn-2" value="Sign In" />
        </form>

        <div class="form-bottom-text">
          <p class="line"></p>
          <p class="cont">Or continue with</p>
          <p class="line"></p>
        </div>

        <div class="icons">
          <img src="#" alt="" />
          <img src="#" alt="" />
          <img src="#" alt="" />
        </div>

        <!-- <div class="footer">
                Don't have an account yet? <a href="#" class="reg">Register</a>
            </div> -->
      </div>
    </section>
  </body>
</html>

Backend/chunkfile/accounts/templates/accounts/sign-up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
         
        body {
            height: 100vh;
        }
        
        /* HEADER */
        header{
            display: flex;
            flex-direction: column;
            gap: 20px;
            margin: 50px;
            padding:0 10rem;
        }
        
        .header-text{
            display: flex;
            justify-content: center;
            font-weight: 400;
        }
        
        
        /* FORM */
        .form-and-image-section {
            display: flex;
            gap: 100px;
            justify-content: center;
            margin-bottom: 77px;
        
        }
        
        .form-section {
            display: flex;
            flex-direction: column;
            gap: 30px;
            margin: 50px;
        }
        
        .form-text {
            font-weight: 400;
        }
        
        form {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }
        
        label {
            display: flex;
            flex-direction: column;
        }
        
        input {
            height: 3rem;
            width: 22rem;
            border-radius: 5px;
            border: none;
            background-color: #d9d9d9;
        }
        
        /* FORM BUTTON */
        button {
            background-color: gray;
            border: none;
            border-radius: 5px;
            height: 3rem;
            width: 22rem;
        
            text-decoration: none;
            font-size: large;
            font-weight: 900;
            color: white;
        }
        
        .form-bottom-text p {
            font-size: 0.95rem;
        }
        
        /* IMAGE */
        .image-section {
            height: 31rem;
            width: 40rem;
            background-color: #d9d9d9;
            margin-top: 60px;
        }
        
        /* FOOTER */
        footer {
            background-color: #d9d9d9;
            height: 5rem;
            display: flex;
            justify-content: center;
        }
        
        .footer-text {
            justify-content: center;
            align-self: center;
        }
        
    </style>
</head>


<body>
    <header>
        <div class="logo">
            <h3>
                CHUNKFILE
            </h3>
        </div>
        <div class="main-header-text">
            <h2 class="header-text">
                Sign Up
            </h2>
        </div>
        
    </header>

    <section class="form-and-image-section">
        <div class="form-section">
            <h3 class="form-text">
                One account for everything split, and more
            </h3>
            <form action="" method="POST">
                {% csrf_token %}
                <label for="email">
                   Username
                </label>
                    {{form.username}}
                <label for="email">
                    Email Address
                </label>
                    {{form.email}}
                <label for="password">
                    Password
                </label>
                    {{form.password1}}
                <label for="Password">
                    Re-enter Password
                </label>
                    {{form.password2}}
                <input type="submit" class="btn-2" value="Create account">
            </form>
           

            <div class="form-bottom-text">
                <p>
                    {% for message in messages %}
                        {{message}}
                    {% endfor %}
                </p>
                <p>
                    <span>Already have an account? <a href="{% url 'accounts:login' %}">Log in</a> </span>
                </p>
                <p>
                    By selecting create account, you agree to our Terms and  <br>
                    have read and acknowledged our Global Privacy Statement
                </p>
            </div>
        </div>
        <div class="image-section">
            <img src="#" alt="">
        </div>
    </section>

    <footer>
        <p class="footer-text">
            Invisible reCAPTCHA by Google Privacy Policy and Terms of Use
        </p>
    </footer>

    <!--Script to add placeholder values to input fields-->
    <script>
        const place_h = document.getElementsByTagName('input');
        place_h[1].placeholder = "ex. john_4454";
        place_h[2].placeholder = "ex. john@doe.com";
    </script>
</body>
</html>

Backend/chunkfile/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>chunked</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&family=Short+Stack&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
  </head>
  <body class="w3-content w3-black" style="max-width: 1500px">
    {% include "navbar.html" %}

    {% block home %} {% endblock home %}
    {% block content %}  {% endblock content %}

    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
      window.cookieconsent.initialise({
        "palette": {
          "popup": {
            "background": "#000"
          },
          "button": {
            "background": "#f1d600"
          }
        },
        "theme": "edgeless",
        "position": "top",
        "static": true,
        "content": {
          "message": "This website uses cookies to ensure you get the best experience on our website", 
          "dismiss": "Got it!",
          "link": "Learn more"
        }
      });
      </script>
      
  </body>
</html>

Backend/chunkfile/main/templates/footer.html
<!-- Footer -->
<footer
class="w3-container w3-padding-32 w3-black w3-center w3-xlarge"
>
<div class="w3-section">
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
</div>
<p class="w3-medium">
  Made with ❤🧡💛💖🤍
  <a
    href="https://www.w3schools.com/w3css/default.asp"
    target="_blank"
    class="w3-hover-text-green"
    ></a
  >
</p>
</footer>

Backend/chunkfile/main/templates/main/documentation.html
{% extends 'base.html' %}
{% load static%}
{% block content %}

   
<h3>Project Name: 
Chunk Files</h3>
<h3>Description of Project:</h3>
<i>Chunked Files is an online platform that allows individuals to upload large CSV or JSON files and split the dataset in the uploaded CSV or JSON file into multiple files.</i>

<h1>Visualization of project description below:</h1>

<div>
<h3>Key Terminologies:</h3>
CSV: A (comma-separated values) file is a simple text file in which information is separated by commas. A CSV file is a plain text file that can be opened in a variety of programs. CSV files are most commonly encountered in spreadsheets and databases. You can use a CSV file to move data between programs that aren't ordinarily able to exchange data. 
</div>
<div>
  JSON: A (JavaScript Object Notation) file is an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values). It is a common data format with diverse uses in electronic data interchange, including that of web applications with servers. 
</div>



<h5>Problem Statement:</h5>
<i>Image below shows one of the problems a data analyst encountered when working with very large files</i>
<div>
  When data analysts or normal individuals want to upload large files of about 3gb or more into certain platforms, it takes too long to complete or the platform may crash as it can’t process that huge file all at once. A good example is a gmail attachment which has a size limit of 25mb, therefore in order to bypass restrictions and send a file of about 500mb to somebody, the individual will have to manually copy and paste data from the main singular file into 20 files of about 25 mb each and send them individually to the recipient.
 <p>
   This presents a huge challenge as it will be very time consuming and cumbersome to perform such an operation. Only if there was a platform that can automatically split the files to the required size within seconds?
 </p>
   <div>
     <h5>Solution Statement</h5>
<p>Fortunately, there are programming languages and platforms that can help automate the splitting of large CSV or JSON files.</p>

<p>With our web application called Chunk Files, manually copying data and splitting them into separate files is now a thing of the past. All you have to do is:</p>
<ol>
  <li>Step 1: Select the file format that you want eg. (.TXT, .XLS, .CSV, .JSON, e.tc)</li>
<li>Step 2: Click on the “Upload File” button and select the desired file from your device or fill in the web link to where the file is located in the input box provided</li>
<li>Step 3: Select the size and dimensions that you want each file to have (Optional)</li>
<li>Step 4: Click on the “Split File” button and wait for the operation to finish and display the various files.</li>
<li>Step 5: Click on the “Download” button or click on “Save file for later” which will allow you to come back later to download even after your session expired or you log out completely. </li>
</ol>

   </div>
</div>


{% endblock %}

Backend/chunkfile/main/templates/main/features.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="topleft">
  <h1>We're currently working on this page 🤔</h1>
</div>
<img src="{% static 'images/comnsoon.png' %}" class="bgimg">
</div>
{% endblock %}

Backend/chunkfile/main/templates/main/home.html
{% extends "base.html" %}
{% load static %}
{% block home %}

<header class="w3-display-container w3-center">
  <div class="w3-padding-64 w3-white">
    <div class="w3-row-padding">
      <div class="w3-col l8 m6">
        <h1 class="w3-jumbo"><b>chunked</b></h1>
        <p>
          <span class="w3-xlarge">Split files anytime and anywhere for <b>FREE!</b> </span> Chunked Files is an online platform that allows individuals to upload large CSV or JSON files and split the dataset in the uploaded CSV or JSON file into multiple files.
        </p>
      </div>
      
      <div class="w3-col l4 m6">
        <h1>We handle file splitting...</h1>
        <img
          src="{% static '/images/split.jpg/' %}"
          class="w3-image w3-right w3-hide-small w3-margin-bottom "
          width="250"
          height="300"
        />
        <h1>...and file conversion</h1>
        <img
          src="{% static '/images/convert.png/' %}"
          class="w3-image w3-right w3-hide-small w3-round"
          width="220"
          height="300"
        />
        
      </div>
    </div>
  </div>
  <div class="w3-padding-64 w3-light-grey">
    <div class="w3-row-padding">
      <div class="w3-col l4 m6">
        <h1>Choose a tool and upload a file</h1>
        <img
          class="w3-image w3-round-large w3-hide-small w3-grayscale"
          src="{% static '/images/up.jpg/' %}"
          alt="App"
          width="335"
          height="471"
        />
        <h1>Download the output file for free</h1>
        <img
        class="w3-image w3-round-large w3-hide-small w3-grayscale"
        src="{% static '/images/down.webp/' %}"
        alt="Download"
        width="335"
        height="471"
      />
      </div>
      <div class="w3-col l8 m6">
        <h1 class="w3-xxxlarge w3-text-red"><b>Got files?</b></h1>
        <p>
          <span class="w3-xlarge">We got tools for you to handle them</span>
          <ul>
            <li>Split large CSV or JSON files and download on the go; Or come back later to download 😃 </li>
            <li>Compress large files into zip and also extract zip files</li>
            <li>Convert from CSV to JSON and vice versa .... we also have more file formats </li>
            <p>Check out our complete services <a href="" onclick="document.getElementById('download').style.display='block'">Here</a>  </p>
          </ul>
        </p>

        <button class="w3-xxxlarge w3-button w3-black"><a href="{% url 'split_file:split_home' %}">Split Files</a> </button>
      </div>
    </div>
  </div>

  <!-- Features Section -->
<div class="w3-container w3-padding-64 w3-dark-grey w3-center">
  <h1 class="w3-jumbo"><b>Qualities</b></h1>
  <p>This is a temporary space-filler</p>

  <div class="w3-row" style="margin-top:64px">
    <div class="w3-col s3">
      <i class="fa fa-bolt w3-text-orange w3-jumbo"></i>
      <p>Fast</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-heart w3-text-red w3-jumbo"></i>
      <p>Loved</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-camera w3-text-yellow w3-jumbo"></i>
      <p>Clarity</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-battery-full w3-text-green w3-jumbo"></i>
      <p>Power</p>
    </div>
  </div>

  <div class="w3-row" style="margin-top:64px">
    <div class="w3-col s3">
      <i class="fa fa-diamond w3-text-white w3-jumbo"></i>
      <p>Sharp</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-cloud w3-text-blue w3-jumbo"></i>
      <p>Cloud</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-globe w3-text-amber w3-jumbo"></i>
      <p>Global</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-hdd-o w3-text-cyan w3-jumbo"></i>
      <p>Storage</p>
    </div>
  </div>
  
  <div class="w3-row" style="margin-top:64px">
    <div class="w3-col s3">
      <i class="fa fa-user w3-text-sand w3-jumbo"></i>
      <p>Safe</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-shield w3-text-orange w3-jumbo"></i>
      <p>Stabile</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-wifi w3-text-grey w3-jumbo"></i>
      <p>Connected</p>
    </div>
    <div class="w3-col s3">
      <i class="fa fa-image w3-text-pink w3-jumbo"></i>
      <p>HD</p>
    </div>
  </div>
</div>
  <p class="w3-padding-64">
    <h3>Why don't you dive right in</h3>
    <a href="{% url 'accounts:login' %}" class="w3-button w3-aqua">Get Started</a>
  </p>
</header>
  {% endblock home %}
  

Backend/chunkfile/main/templates/navbar.html
{% load static %}
<div id="navbar">
    <ul>
        <li class="side-menu-open"><a href="{% url 'main:home' %}">ᑕᕼᑌᑎᛕᗴᗪ</a></li>
        <li><a href="">Dashboard</a></li>
        <li><a href="{% url 'main:features' %}">Our Services</a></li>
        <li><a href="{% url 'main:features' %}">Suggest new features</a></li>

        <li><a href="{% url 'main:documentation' %}">Documentation</a></li>
        <li><a href="{% url 'split_file:split_home' %}">Get Started</a></li>
        <span><b class='fa fa-user w3-button'>{{request.user}}</b></span>
        <a href="{% url 'accounts:logout' %}" class="w3-button">Log out</a>

    </ul>
</div>
{% block content %}
{% endblock %}

Backend/chunkfile/split_file/templates/split_file/split_csv.html
{% extends 'split_home.html' %}
{% load static %}

{% block content %}

<div id="upload">
    <input type="file" id="file" />
    <input type="submit" value="Split" class="w3-button w3-padding-16 w3-black">
</div>


{% endblock %}

Backend/chunkfile/split_file/templates/split_file/split_json.html
{% extends 'split_home.html' %}
{% load static %}

{% block content %}

<div id="upload">
    <input type="file" id="file" />
    <input type="submit" value="Split" class="w3-button ">
</div>


{% endblock %}

Backend/chunkfile/split_file/templates/split_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<script src="https://kit.fontawesome.com/c1c26ed80d.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'split_file/css/style.css' %}">
<script src="{% static 'split_file/js/index.js' %}"></script>
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-padding-large w3-hover-white w3-large w3-black" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="{% url 'main:home' %}" class="w3-bar-item w3-button w3-padding-large w3-white">ᑕᕼᑌᑎᛕᗴᗪ</a>
    <a href="{% url 'split_file:split_home' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Split</a>
    <a href="{% url 'main:features' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Our features</a>
    <a href="{% url 'main:documentation' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Documentation</a>
    <span><b class='fa fa-user w3-button w3-right'>{{request.user}}</b></span>
    <a href="{% url 'accounts:logout' %}" class="w3-right w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Log out</a>
</div>
{% block content %}
  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="{% url 'main:home' %}" class="w3-bar-item w3-button w3-padding-large">ᑕᕼᑌᑎᛕᗴᗪ</a>
    <a href="{% url 'split_file:split_home' %}" class="w3-bar-item w3-button w3-padding-large">Split</a>
    <a href="{% url 'main:features' %}" class="w3-bar-item w3-button w3-padding-large">Suggest New Feature</a>
    <a href="{% url 'main:documentation' %}" class="w3-bar-item w3-button w3-padding-large">Documentation</a>
      <span><b class='fa fa-user'>{{request.user}}</b></span>
      <a href="{% url 'accounts:logout' %}" class="w3-button w3-grey w3-border-radius">Log out</a>
  </div>
</div>

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">🆂🅿🅻🅸🆃</h1>
  <p class="w3-large">What would you like to split today?</p>
</header>

<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
      <h5 class="w3-padding-32 w3-jumbo">
        Split csv files
      </h5>
      <a href="{% url 'split_file:split_csv' %}" class="w3-button w3-padding-32 w3-grey w3-center w3-hover-red">
        Start splitting
      </a>
    </div>

    <div class="w3-third w3-center">
      <img src="{% static 'split_file/images/csv-icon.png' %}" alt="csv" class="w3-padding-64 w3-text-red">
    </div>
  </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-third w3-center">
        <img src="{% static 'split_file/images/json-file-icon.jpg' %}" alt="json" class="w3-padding-64 w3-text-red w3-margin-right">
    </div>

    <div class="w3-twothird">
      <h5 class="w3-padding-32 w3-jumbo">
        Split json files
      </h5>
        <a href="{% url 'split_file:split_json' %}" class="w3-button w3-padding-32 w3-grey w3-center w3-hover-red">
          Start splitting
        </a>
    </div>
  </div>
</div>

<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
</div>
{% endblock %}

{% include 'footer.html' %}

</body>
</html>